var VIDEO_DATA = [
    //{"youtubeID": "XVLaneDac6U", "name": "When You're Smiling"},
    {"youtubeID": "Vf0E0Ypydms", "name": "Komm, lieber Mai"},
    {"youtubeID": "4zIPNWFBEDs", "name": "Rothenburger Wellerman"},
    {"youtubeID": "Oa_ULKizeU8", "name": "Our Father"},
    {"youtubeID": "4qNsrNTrWao", "name": "Auf, du junger Wandersmann & Es wollt ein Jägerlein jagen"},
    {"youtubeID": "ovJkFaCK9u0", "name": "Peace I Leave With You"},
    {"youtubeID": "h0NY6_KPQrA", "name": "Imagine"},
    //{"youtubeID": "oT8KKG6y7rI", "name": "Roar"},
    {"youtubeID": "0Uan1b-FmKM", "name": "Fair Phyllis I saw sitting all alone"},
    {"youtubeID": "Ty398uSyBKA", "name": "Rolling in the Deep"},
    {"youtubeID": "1Z9mkwWCC-8", "name": "Schöner Frühling, komm doch wieder"},
    {"youtubeID": "E4v3psrBfYY", "name": "Der Garten der goldenen Äpfel"},
    {"youtubeID": "CjYQrlYbU6k", "name": "Wenn die Sonja russisch tanzt"},
    //{"youtubeID": "jtsBAzynahs", "name": "Щедрик | Schtschedryk"},
    //{"youtubeID": "XxssNko2Sy4", "name": "Steigerlied"},
    //{"youtubeID": "XMThkrfflrw", "name": "Schatten"},
    //{"youtubeID": "gNwLEiSJoHg", "name": "Mögen sich die Wege"},
    {"youtubeID": "sbbKZeAJoPE", "name": "Caroling, Caroling"},
    {"youtubeID": "RuNTXGGd9x8", "name": "Evening Rise"},
    {"youtubeID": "qlAKbZ5WRBk", "name": "Auf die Hundertjährige"},
    {"youtubeID": "0fo8_6O_Gc4", "name": "todo cambia"},
    {"youtubeID": "Vf0E0Ypydms", "name": "Frühlingsgruß"},
    {"youtubeID": "ba3M1o-ocD8", "name": "Gemeinsam"},
    {"youtubeID": "rErveIfp658", "name": "Lobet den Herrn "},
    {"youtubeID": "dQLMRUCmY0U", "name": "#zusammen SINGEN wir STÄRKER"},
    {"youtubeID": "xK3kuP_0-_I", "name": "Bel ami"},
    {"youtubeID": "YUULTTzV178", "name": "Nicodéchor Langebrück - Frühlingskonzert"},
    {"youtubeID": "AaBPCcGQtdw", "name": "Imagine"}
];


